### ISSUE TITLE
Error while documenting

### ISSUE THREAD

**Issue by Dragonink** [ZettaScaleLabs/stabby#30]
I am trying to document your crate, but `cargo doc` (and the docs.rs version as well) fails with this error:
**[E0080] evaluation of constant value failed**

The error happens at this line:
https://github.com/ZettaScaleLabs/stabby/blob/cbc6014ff8fca5b5107793a6e60691d5b73b9a48/stabby-abi/src/typenum2/unsigned.rs#L238

**Comment by p-avital** [comment]
Hi, I think every doc issue has been addressed by recent changes (notably regarding the new tutorial), so I'll close this issue now :)
