### ISSUE TITLE
Can Not Stablize Traits that has methods that return trait objects Dyn or DynRef

### ISSUE THREAD

**Issue by ZakharEl** [ZettaScaleLabs/stabby#60]
```rust
#[stabby::stabby]
pub trait Segment {
	extern "C" fn display(&self) -> stabby::string::String;
	extern "C" fn update(&self, update: stabby::string::String);
}

#[stabby::stabby]
pub trait Snippet {
	extern "C" fn display(&self) -> stabby::string::String;
	extern "C" fn get_children(&'s self) -> stabby::vec::Vec<stabby::DynRef<'s, stabby::vtable!(Segment)>>;
}
```
This example refuses to compile. How do I return a ABI stable trait object from another stable trait's method?

**Comment by p-avital** [comment]
Hi there,

That's strange, I'll look at this as soon as I'm back from holiday (I don't have a PC on hand for the week)...

In the meantime, can you provide:
- Your Rust version?
- The error that Rust gives you for the snippet you've provided?

Thanks for letting me know about that :)

**Comment by ZakharEl** [comment]
![2024-03-19-124924_1233x454_scrot](https://github.com/ZettaScaleLabs/stabby/assets/45983690/9328c174-c5cc-4155-878e-da61ad1a3dea)
Rust version: rustc 1.69.0 (84c898d65 2023-04-16)
Error mesage: error: custom attribute panicked
 --> src/lib.rs:7:1
  |
7 | #[stabby::stabby]
  | ^^^^^^^^^^^^^^^^^
  |
  = help: message: stabby couldn't see through a macro in type position. Try using a type alias :)

error: could not compile `snippet-traits` due to previous error

**Comment by ZakharEl** [comment]
![2024-03-19-125345_1225x329_scrot](https://github.com/ZettaScaleLabs/stabby/assets/45983690/ec1f92d9-784b-401f-99a7-5e110dd9e8bf)
Stabby version used: 3.0.3
since that version is the latest version that builds the 4. something version that you have does not compile as stated on the rust docs. According to the rust docs the latest version that builds is 3.0.3.
The cargo edition is 2021 as shown in my Cargo.toml file. Thanks by the way for your hard work on this project!

**Comment by p-avital** [comment]
Ah, there you go, it's telling you what to do: use a typedef like this:
```rust
type DynSegmentRef<'a> = stabby::dynptr!(&'a dyn Segment);
```
And then use that name as the return type in your trait :)

This is needed because, as the error says, stabby can't tell what the macro will expand to, so it goes on the careful side and asks you to provide a type name instead so that it's sure it won't be fooled.

It's also needed because stabby wouldn't know how to rebind lifetimes in the vtable generation through macros.

**Comment by p-avital** [comment]
> Stabby version used: 3.0.3 since that version is the latest version that builds the 4. something version that you have does not compile as stated on the rust docs. According to the rust docs the latest version that builds is 3.0.3.

This is because rustdoc uses `nightly` which made a breaking change. I have a fix pending, but am about 1500km from my PC at the moment, so it'll have to wait next week :)

**Comment by ZakharEl** [comment]
Thank you! It works. If you want I can put a pull request with examples for stable traits displaying this.

**Comment by p-avital** [comment]
That would be lovely, thank you :)

**Comment by p-avital** [comment]
Hi, I've now done a proper tutorial that should help newcomers avoid the issues you faced, so I'm closing this issue :)
