### ISSUE TITLE
MSRV regression

### ISSUE THREAD

**Issue by yellowhatter** [ZettaScaleLabs/stabby#71]
This problem is related to #58 

After the last 5.0.0 release build for < 1.78.0 is broken

You can reproduce with command like this:
`cargo +1.73.0 clippy --all-targets -- --deny warnings`
or simply
`cargo +1.73.0 build`

**Comment by yellowhatter** [comment]
We fix it like this: #72

**Comment by p-avital** [comment]
#73 (published as `5.0.1`) closes this issue
