### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by TCROC** [ZettaScaleLabs/stabby#8]
Does stabby currently have a license? I couldn't find one when browsing the repo.

Thanks! :)

**Comment by p-avital** [comment]
Thanks for the tip, I forgot to add a license to the repo itself.

As the headers in each file and the license fields in all `Cargo.toml` files state: this project is under EPL-2.0 OR Apache-2.0 licensing :)

**Comment by TCROC** [comment]
Thanks! I saw your post on Reddit and look forward to hearing you at Rustcon :)
